apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
spec:
  replicas: 5
  selector:
    app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: kubeguide/tomcat-app: v1
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_SERViCE_HOST
          Value: 'mysql'
        - name: MYSQL_SERVICE_PORT
          Value: '3306'
